const GTM = process.env.GTM;
const REALM_APP_ID = process.env.REALM_APP_ID;
const REALM_APP_KEY = process.env.REALM_APP_KEY;
const MAPBOX_ACCESS_TOKEN = process.env.MAPBOX_ACCESS_TOKEN;
const MAPBOX_HEIGHT =  process.env.MAPBOX_HEIGHT;
const MAPBOX_FONT_COLOR_1 =  process.env.MAPBOX_FONT_COLOR_1;
const MAPBOX_HEADING_BACKGROUND_COLOR =  process.env.MAPBOX_HEADING_BACKGROUND_COLOR;
const MAPBOX_ZOOM =  process.env.MAPBOX_ZOOM;
const MAPBOX_LAT =  process.env.MAPBOX_LAT;
const MAPBOX_LNG =  process.env.MAPBOX_LNG;
const MAPSTUFF_OWNER_EMAIL = process.env.MAPSTUFF_OWNER_EMAIL;
const MAPBOX_STYLE = process.env.MAPBOX_STYLE;
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
const STRIPE_PUBLISHABLE_KEY = process.env.STRIPE_PUBLISHABLE_KEY;
const STRIPE_PRICE_FREE = process.env.STRIPE_PRICE_FREE;
const STRIPE_PRICE_LITE = process.env.STRIPE_PRICE_LITE;
const STRIPE_PRICE_PLUS = process.env.STRIPE_PRICE_PLUS;
const STRIPE_PRICE_PREMIUM = process.env.STRIPE_PRICE_PREMIUM;
const DB_DATABASE = process.env.DB_DATABASE;
module.exports = {
  env: {
    GTM: GTM,
    REALM_APP_ID: REALM_APP_ID,
    REALM_APP_KEY: REALM_APP_KEY,
    MAPBOX_ACCESS_TOKEN: MAPBOX_ACCESS_TOKEN,
    MAPBOX_HEIGHT: MAPBOX_HEIGHT,
    MAPBOX_FONT_COLOR_1: MAPBOX_FONT_COLOR_1,
    MAPBOX_HEADING_BACKGROUND_COLOR: MAPBOX_HEADING_BACKGROUND_COLOR,
    MAPBOX_ZOOM: MAPBOX_ZOOM,
    MAPBOX_LAT: MAPBOX_LAT,
    MAPBOX_LNG: MAPBOX_LNG,
    MAPBOX_STYLE: MAPBOX_STYLE,
    STRIPE_SECRET_KEY: STRIPE_SECRET_KEY,
    STRIPE_PUBLISHABLE_KEY: STRIPE_PUBLISHABLE_KEY,
    STRIPE_PRICE_FREE: STRIPE_PRICE_FREE,
    STRIPE_PRICE_LITE: STRIPE_PRICE_LITE,
    STRIPE_PRICE_PLUS: STRIPE_PRICE_PLUS,
    STRIPE_PRICE_PREMIUM: STRIPE_PRICE_PREMIUM,
    MAPSTUFF_OWNER_EMAIL: MAPSTUFF_OWNER_EMAIL,
    DB_DATABASE: DB_DATABASE,
  },
  i18n: {
    locales: ["en", "fr"],
    defaultLocale: "en",
  },
  swcMinify: false,
};
